const chats = [
  {
    hote: null,
    nom: 'Myu',
    age: 2,
    image: 'myu.jpg',
    like: false,
    description:
      "Chat le plus adorable du monde qui ne pense qu'avec son estomac et aime un peu trop se cacher dans les sacs de course.",
    vaccin: true,
    sexe: 'F',
  },
  {
    hote: null,
    nom: 'Isaac Newton',
    age: 13,
    image: 'gatto.jpg',
    like: false,
    description:
      'Elle griffe toutes les personnes dont le prénom commence par "A"',
    vaccin: true,
    sexe: 'F',
  },
  {
    hote: null,
    nom: 'Clara',
    age: 18,
    image: 'clara.jpg',
    like: false,
    description: 'Agée mais excellent chasseuse. adore les chauvres-souris',
    vaccin: true,
    sexe: 'F',
  },
  {
    hote: null,
    nom: 'Ice',
    age: 1,
    image: 'ice.jpg',
    like: false,
    description: 'Ice est un jeune chat qui mange tout sur son chemin.',
    vaccin: true,
    sexe: 'F',
  },
  {
    hote: null,
    nom: 'Wibe',
    age: 3,
    image: 'wibe.jpg',
    like: false,
    description: 'Wibe est un tout petit chat très affectuex mais des fois trop grognon',
    vaccin: true,
    sexe: 'M',
  },
  {
    hote: null,
    nom: 'Athena',
    age: 8,
    like: false,
    description: 'Athena est un sphynx qui pète souvent mais qui est adorable',
    vaccin: true,
    sexe: 'F',
    image: 'athena.jpg',
  },
  {
    hote: null,
    nom: 'Gucci',
    age: null,
    image: 'gucci.jpg',
    like: false,
    description: 'Chat magnifique, hyper calin mais grateur professionnel de nourriture et d attention. Habituer de cohabitater avec des chiens. Gucci est attacher à son indépendance ( peut partir en vadrouille dehors toute une journée / nuit) ',
    vaccin: true,
    sexe: 'M',
  },
  {
    hote: null,
    nom: 'Asaliah',
    age: 12,
    image: 'asaliah.jpg',
    like: false,
    description: 'Asaliah est un vieux chat un peu aigri.',
    vaccin: true,
    sexe: 'F',
  },
  {
    hote: null,
    nom: 'Charlie',
    age: 3,
    image: 'charlie.jpg',
    like: false,
    description: 'Chat adopté à la spa, tigré et très mignon',
    vaccin: false,
    sexe: 'F',
  },
  {
    hote: null,
    nom: 'Popops',
    age: 13,
    image: 'popops.jpg',
    like: false,
    description: "Le plus beau des chats et le plus affectueux mais il a l'habitude d'uriner sur les coussins",
    vaccin: true,
    sexe: 'F',
  },
  {
    hote: null,
    nom: 'Arrakis',
    age: 10,
    image: 'arrakis.jpg',
    like: false,
    description:
      'Chat mâle à poils long, extrêment calin, ne demande qu\'à vous servir d\'écharpe',
    vaccin: true,
    sexe: 'M',
  },
  {
    hote: null,
    nom: 'Johny',
    age: 13,
    image: 'johnylebourge.jpg',
    like: false,
    description:
      'Johny aime manger du saumon et du caviar. Il vit sa best-life, car sa maîtresse est multimilliardaire.',
    vaccin: true,
    sexe: 'M',
  },
  {
    hote: null,
    nom: 'Tanguy',
    age: 12,
    image: 'tanguy.jpg',
    like: false,
    description: 'Chat paresseux et bien gras. Un bon matou',
    vaccin: true,
    sexe: 'M',
  },
];
